#Auth:Qing.Yu
#Mail:1753330141@qq.com
# Ver:V1.2
#Date:2018-07-01
---
- hosts: oradb
  remote_user: root
  tasks:
  - name: backup ORADB
    remote_user: oracle
    script: /root/Ansible_Playbook/Script/bakProc_ORADB_Remote.sh

  - name: archivelog maintenance
    remote_user: oracle
    script: /root/Ansible_Playbook/Script/archivelog_maintenance.sh

  - name: list dmp files
    remote_user: oracle
    find:
      paths: /media/ORADB/DBSoftware/app/oracle/admin/OAPROD8/dpdump/
      patterns: "*.dmp"
    register: file_2_fetch 

  - name: move dmp files to File Server
    remote_user: oracle
    fetch: 
      src: "{{ item.path }}"
      dest: /root/bakORADB/bakFolder/
      flat: yes
    with_items: "{{ file_2_fetch.files }}"
   
  - name: remove dump files
    remote_user: oracle
    file:
      path: "{{ item.path }}"    
      state: absent
    with_items: "{{ file_2_fetch.files }}"

- hosts: zabbix
  tasks:
  - name: bakResult
    remote_user: root
    #测试
    shell: bash /root/Ansible_Playbook/Script/bakResult.sh

